# Generated by Django 5.0.3 on 2024-03-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idol', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cd',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='idol',
            name='birthplace',
            field=models.CharField(db_comment='出身地', max_length=10),
        ),
        migrations.AlterField(
            model_name='idol',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='idol',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
